home/urls.py
from django.urls import path

from . import views

app_name = 'home'

urlpatterns = [
    path('', views.index, name='index'),
    path('more/', views.more, name='more'),
]

story_1/urls.py
from . import views
from django.urls import path

app_name = 'story1'

urlpatterns = [
    path('', views.index, name="index")
]

story_4/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls', namespace = 'home')),
    path('story_1/', include('story_1.urls')),
]

home/models.py
from django.db import models

# Create your models here.

story_1/models.py
from django.db import models

# Create your models here.

home/views.py
from django.shortcuts import render

# Create your views here.

def index(request):
    return render(request, 'home/index.html')

def more(request):
     return render(request, 'home/more.html')

story_1/views.py
from django.shortcuts import render

# Create your views here.

def index(request):
    return render(request, 'story_1/index.html')

home/templates/home/base.html
<!DOCTYPE html>
<html lang="en">

{% load static %}

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% block css %}
        
    {% endblock css %}
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    {% block title %}
        
    {% endblock title %}
</head>

<body>
    <div id="navbar">
        <img id="logo" src="{% static 'home/images/logo-2.png' %}" alt="logo" height="50">
        <div class="d-flex justify-content-end">
            <div class="menu p-2 bd-highlight"><a href="{% url 'home:index' %}" class="navigation"> Home </a> &nbsp;</div>
            <div class="menu p-2 bd-highlight"><a href="{% url 'home:index' %}#education" class="navigation"> Education </a> &nbsp;</div>
            <div class="menu p-2 bd-highlight"><a href="{% url 'home:index' %}#experience" class="navigation"> Experience </a> &nbsp;</div>
            <div class="menu p-2 bd-highlight"><a href="{% url 'home:more' %}" class="navigation"> More </a> &nbsp;</div>
            <div class="menu p-2 bd-highlight"><a href="{% url 'story1:index' %}" class="navigation"> Story1 </a> &nbsp;</div>
        </div>
    </div>
    {% block content %}
        
    {% endblock content %}
    <section id="footer">
        <div>
            <img id="footer" src="{% static 'home/images/footer.png' %}" alt="footer">
        </div>
    </section>
</body>

home/templates/home/index.html
{% extends 'home/base.html' %}

{% load static %}

{% block css %}
<link rel="stylesheet" href="{% static 'home/style.css' %}">
{% endblock css %}

{% block title %}
<title>Andhikuy!</title>
{% endblock title %}

{% block content %}
    

    <section id="home">
        <div id="konten-home" class="d-flex bd-highlight mb-3">
            <div class="mr-auto p-2 bd-highlight"><p>Halo! Nama saya Andhika Rifki Alfariz. Teman-teman biasa memanggil saya Andhika. Saya adalah seorang mahasiswa Fasilkom Universitas Indonesia. Saya adalah orang yang cukup aktif dan gemar bersosialisasi dengan banyak orang.</p></div>
            <div class="p-2 bd-highlight"><img id="foto-andhika" src="static/home/images/andhika-1.png" alt="foto-Andhika" height="400"></div>
          </div>
        </div>
    </section>

    <section id="education">
        <h1>Education</h1>
        <img class="line" src="static/home/images/Line.png" alt="Line">
        
        <div class="d-flex justify-content-around">
            <figure class="logo-pendidikan">
                <img id="SD-1" src="static/home/images/Nurul-Fatimah.jpg" alt="SDI-Nurul-Fatimah" height="200">
                <figcaption>SDI Nurul Fatimah<br>2007-2010</figcaption>
            </figure>
        
            <figure class="logo-pendidikan">
                <img id="SD-2" src="static/home/images/Alfalah.png" alt="SDI-Al-Falah-1-Pagi" height="200">
                <figcaption>SDI Al-Falah 1 Pagi<br>2010-2013</figcaption>
            </figure>

            <figure class="logo-pendidikan">
                <img id="SMP" src="static/home/images/SMPN-111.png" alt="SMPN-111-Jakarta" height="200">
                <figcaption>SMPN 111 Jakarta<br>2013-2016</figcaption>
            </figure>
        </div>
        
        <div class="d-flex justify-content-around">
            <figure class="logo-pendidikan">
                <img id="SMA" src="static/home/images/SMAN78.png" alt="SMAN-78-Jakarta" height="200">
                <figcaption>SMPN 78 Jakarta<br>2016-2019</figcaption>
            </figure>

            <figure class="logo-pendidikan">
                <img id="Kuliah" src="static/home/images/Fasilkom.png" alt="Fasilkom-UI" height="200">
                <figcaption>Fasilkom UI<br>2019-Sekarang</figcaption>
            </figure>   
        </div>
    </section>

    <section id="experience">
        <h1>Experience</h1>
        <img class="line" src="static/home/images/Line.png" alt="Line">
        <div class="d-flex justify-content-around">
            <figure class="logo-organisai">
                <img id="rohis78" src="static/home/images/logo-rohis.png" alt="Rohis-78" height="200">
                <figcaption>Ketua Umum<br>Rohis78 2017-2018</figcaption>
            </figure>

            <figure class="logo-organisai">
                <img id="pemira" src="static/home/images/pemira.png" alt="Pemira-Fasilkom" height="200">
                <figcaption>Staf Pemungutan Suara<br>Pemira Fasilkom UI 2019</figcaption>
            </figure>
        </div>

        <div class="d-flex justify-content-around">
            <figure class="logo-organisai">
                <img id="bem" src="static/home/images/logo-bem.png" alt="BEM-Fasilkom" height="200">
                <figcaption>Staf Kajian dan Aksi Strategis<br>BEM Fasilkom UI 2020</figcaption>
            </figure>
            
            <figure class="logo-organisai">
                <img id="siwak" src="static/home/images/siwak.png" alt="SIWAK-NG" height="200">
                <figcaption>PJ Akomodasi<br>SIWAK-NG 2020</figcaption>
            </figure>
        </div>

        <div class="d-flex justify-content-around">
            <figure class="logo-organisai">
                <img id="fuki" src="static/home/images/FUki.png" alt="FUKI-Fasilkom" height="200">
                <figcaption>Staf Kemakmuran Musholla FUKI<br>FUKI Fasilkom UI 2020</figcaption>
            </figure>

            <figure class="logo-organisai">
                <img id="rk" src="static/home/images/rk-warna.png" alt="Rumah-Kepemimpinan" height="200">
                <figcaption>Peserta Rumah Kepemimpinan<br>Ksatria X Jakarta</figcaption>
            </figure>   
        </div>
    </section>

{% endblock content %}

home/templates/home/more.html
{% extends 'home/base.html' %}

{% load static %}

{% block css %}
<link rel="stylesheet" href="{% static 'home/style.css' %}">
{% endblock css %}

{% block title %}
<title>Andhikuy! - More</title>
{% endblock title %}

{% block content %}

<section id="more">
    <h1>More About Me</h1>
    <img class="line" src="{% static 'home/images/Line.png' %}" alt="Line">
    
    <div class="d-flex justify-content-around">
        <div>
            <h2>Hobi</h2>
            <ul>
                <li>Futsal</li>
                <li>Badminton</li>
                <li>Berenang</li>
                <li>Gaming</li>
            </ul>
        </div>
        <div>
        <h2>Interest</h2>
        <ul>
            <li>Cyber Security</li>
            <li>Social</li>
            <li>Politics</li>
            <li>Gaming</li>
            <li>Anime</li>
            <li>Movies</li>
        </ul>
        </div>
    </div>
</section>

{% endblock content %}

story_1/templates/story_1/index.html
<!DOCTYPE html>
<html lang="en">

{% load static %}

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'home/style.css' %}">
    <title>Andhika!</title>
</head>
<body >
        <div id="page">
            <h1>Andhika Rifki Alfariz</h1>
            <h2>1906398345</h2>
            <h2>Ilmu Komputer - Universitas Indonesia</h2>
            <h2>About Me</h2>
            <p>
                Saya adalah satu dari 7,7 miliar orang yang tinggal di bumi. Bernapas dengan udara dan makan makanan yang lezat dan tentunya bergizi.
                Tak terasa sudah 19 tahun saya menjalani kehidupan. Saya habiskan waktu hidup untuk melakukan kegiatan seperti orang-orang pada umumnya.
                Bangun pagi, mandi, tidak lupa menggosok gigi, habis mandi ku tolong ibu membersihkan tempat tidurku. Tidak lupa menyalakan TV lalu
                menonton Spongebob sambil sarapan. Berangkat sekolah, belajar dan bertemu teman-teman yang kadang menyebalkan tapi selalu ada jika dibutuhkan.
                Pulang dengan bahagia sambil menebak-nebak masakan apa yang dibuat mama di rumah. 
            </p>
            
            <img src="{% static 'home/images/andhika.jpg' %}" height="500"> 
            <!-- <p>*Aku yang kanan bukan yang kiri</p>   -->

            <h2>Ini adalah daftar hobi saya!</h2>
                <ul>
                    <li>Minum Coklat Panas</li>
                    <li>Menonton TV</li>
                    <li>Menyusun Puzzle</li>
                    <li>Bermain Permainan Papan</li>
                    <li>Bermain Tic Tac Toe</li>
                </ul>
            
            <h2>Riwayat pendidikan</h2>
            <table border="1">
                <tr>
                    <th>No.</th>
                    <th>Jenjang</th>
                    <th>Nama Institusi</th>
                    <th>Tahun</th>
                </tr>
                <tr>
                    <td>1.</td>
                    <td>TK</td>
                    <td>TK Nurul Fatimah</td>
                    <td>2005 - 2007</td>
                </tr>
                <tr>
                    <td>2.</td>
                    <td>SD</td>
                    <td>SDI Nurul Fatimah</td>
                    <td>2007-2010</td>
                </tr>
                <tr>
                    <td>3.</td>
                    <td>SD</td>
                    <td>SDI Al-Falah 1 Pagi</td>
                    <td>2010-2013</td>
                </tr>
                <tr>
                    <td>4.</td>
                    <td>SMP</td>
                    <td>SMPN 111 Jakarta Barat</td>
                    <td>2013-2016</td>
                </tr>
                <tr>
                    <td>5.</td>
                    <td>SMA</td>
                    <td>SMAN 78 Jakarta Barat</td>
                    <td>2016-2019</td>
                </tr>
                <tr>
                    <td>6.</td>
                    <td>Perguruan Tinggi</td>
                    <td>Universitas Indonesia</td>
                    <td>2019 - sekarang</td>
                </tr>
            </table>


            <h2>Click to Find Me!</h2>
                <a href="https://www.instagram.com/andhikalfariz" target="_blank"><img src="static/home/images/instagram.png" height="50"></a> 
                <a href="https://www.facebook.com/andhikalfariz" target="_blank"><img src="static/home/images/facebook.png" height="50"></a>
                <a href="https://www.linkedin.com/in/andhika-rifki-alfariz-681bbb193/" target="_blank"><img src="static/home/images/linkedin.png" height="50"</a> 
        </div>
    </body> 
</html>